# Generated by Django 3.2.10 on 2022-03-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'Free delivery')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
