# Generated by Django 3.2.10 on 2022-03-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
